### model
model_name_or_path: /mnt/zhongziban/peixunban/001526_zdd/OLMo/hf_checkpoint_dir/OLMo-1B_gtbs2048_dtms2_md1e_ddp_compile_nh/step23500-unsharded
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
# deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: identity, tulu-3-sft-mixture
template: olmo
cutoff_len: 2048
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/olmo1b_s235h/full/sft/tulu_3
logging_steps: 10
save_steps: 200
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.0
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 200


###yaml
report_to: wandb
run_name: olmo1b_s235h_full_sft_tulu_3

